root: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2021
  sourceType: module
  arrowFunctions: true
  project: './tsconfig.json'
env:
  es6: true
extends:
  - 'eslint:recommended'
  - 'plugin:prettier/recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
plugins:
  - import
  - prefer-arrow
  - prettier
  - '@typescript-eslint'
rules:
  array-callback-return: error
  block-scoped-var: error
  complexity:
    - error
    - 10
  consistent-this: error
  eol-last: error
  eqeqeq: error
  func-name-matching: error
  func-style:
    - error
    - declaration
    - allowArrowFunctions: true
  linebreak-style: error
  max-nested-callbacks:
    - error
    - 3
  max-params:
    - error
    - 3
  new-cap: error
  new-parens: error
  newline-per-chained-call:
    - error
    - ignoreChainWithDepth: 2
  no-bitwise: error
  no-caller: error
  no-confusing-arrow: warn
  no-console: error
  no-duplicate-imports: error
  no-empty: error
  no-empty-function: error
  no-eval: error
  no-extend-native: error
  no-extra-bind: error
  no-extra-label: error
  no-extra-boolean-cast: error
  no-implicit-coercion:
    - error
    - allow:
        - '!!'
  no-implicit-globals: error
  no-implied-eval: error
  no-invalid-this: error
  no-label-var: error
  no-lone-blocks: error
  no-lonely-if: error
  no-loop-func: error
  no-multi-assign: error
  no-multiple-empty-lines: error
  no-new: error
  no-new-func: error
  no-new-object: error
  no-new-wrappers: error
  no-octal-escape: error
  no-param-reassign: error
  no-promise-executor-return: error
  no-proto: error
  no-redeclare: off
  no-return-assign:
    - error
    - always
  no-return-await: off
  no-self-compare: error
  no-sequences: error
  no-shadow: off
  no-tabs: error
  no-template-curly-in-string: error
  no-throw-literal: off
  no-trailing-spaces: error
  no-underscore-dangle:
    - error
    - allowAfterThis: true
      allowFunctionParams: true
  no-unneeded-ternary: error
  no-unused-expressions: off
  no-unused-vars: off
  no-use-before-define: off
  no-useless-call: error
  no-useless-computed-key: error
  no-useless-concat: error
  no-useless-constructor: off
  no-useless-rename: error
  no-useless-return: error
  no-var: error
  prefer-arrow-callback: error
  prefer-const: error
  prefer-promise-reject-errors: error
  prefer-rest-params: error
  prefer-spread: error
  radix: error
  require-atomic-updates: error
  require-await: error
  spaced-comment: error
  yoda: error
  'import/order':
    - error
    - groups:
        - builtin
        - external
        - internal
        - parent
        - sibling
        - index
        - object
        - type
      newlines-between: always
      alphabetize:
        order: asc
        caseInsensitive: false
  'prefer-arrow/prefer-arrow-functions':
    - error
    - disallowPrototype: true
  '@typescript-eslint/consistent-indexed-object-style':
    - error
    - record
  '@typescript-eslint/default-param-last': error
  '@typescript-eslint/explicit-module-boundary-types':
    - error
    - allowDirectConstAssertionInArrowFunctions: true
      allowHigherOrderFunctions: true
  '@typescript-eslint/member-delimiter-style': error
  '@typescript-eslint/method-signature-style':
    - error
    - property
  '@typescript-eslint/no-confusing-non-null-assertion': error
  '@typescript-eslint/no-confusing-void-expression': error
  '@typescript-eslint/no-duplicate-imports': error
  '@typescript-eslint/no-empty-function': error
  '@typescript-eslint/no-extraneous-class': error
  '@typescript-eslint/no-invalid-void-type': error
  '@typescript-eslint/no-meaningless-void-operator': error
  '@typescript-eslint/no-misused-new': error
  '@typescript-eslint/no-misused-promises': error
  '@typescript-eslint/no-non-null-asserted-nullish-coalescing': error
  '@typescript-eslint/no-redeclare': error
  '@typescript-eslint/no-shadow': error
  '@typescript-eslint/no-throw-literal':
    - error
  '@typescript-eslint/no-unnecessary-boolean-literal-compare': error
  '@typescript-eslint/no-unnecessary-condition': error
  '@typescript-eslint/no-unnecessary-type-arguments': error
  '@typescript-eslint/no-useless-constructor':
    - error
  '@typescript-eslint/non-nullable-type-assertion-style': error
  '@typescript-eslint/prefer-for-of': error
  '@typescript-eslint/prefer-includes': error
  '@typescript-eslint/prefer-literal-enum-member': error
  '@typescript-eslint/prefer-nullish-coalescing': error
  '@typescript-eslint/prefer-readonly': error
  '@typescript-eslint/prefer-reduce-type-parameter': error
  '@typescript-eslint/prefer-string-starts-ends-with': error
  '@typescript-eslint/prefer-ts-expect-error': error
  '@typescript-eslint/require-array-sort-compare': error
  '@typescript-eslint/return-await': error
  '@typescript-eslint/strict-boolean-expressions': error
  '@typescript-eslint/switch-exhaustiveness-check': error
  '@typescript-eslint/unified-signatures': error
  '@typescript-eslint/prefer-optional-chain': error
  '@typescript-eslint/no-unused-vars':
    - error
    - args: none
  '@typescript-eslint/no-unused-expressions':
    - error
    - allowShortCircuit: true
      allowTernary: true
